server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
  application:
    name: category-service
  profile: default
appDescription: "Category API"
appVersion: "1.0.0"
